### ISSUE TITLE
Please help me！！！

### ISSUE THREAD

**Issue by ShineyYao** [quyctd/myclass-clone#13]
when I use python manage.py runserver ,It turned out that
**System check identified no issues (0 silenced).
March 11, 2021 - 11:31:12
Django version 3.1.7,  using settings None
Starting development server at http://127.0.0.1:8000/**
And I think "using settings None"have some thing wrong.

and when I use the website,It turned out that 
A server error occurred.  Please contact the administrator.

Then I returned the commend shell, It has the error that
AttributeError: module 'django.conf.global_settings' has no attribute 'ROOT_URLCONF'
But I really don't find  'django.conf.global_settings' in the file.

And can you tell me where is the database,I really can't find it.
I would be most grateful if you could answer my questions.

**Comment by quyctd** [comment]
Sorry for the late reply.

I think the reason is you're using Django version 3.1.7, but the support version of this project is 2.2. So it's lead to the error: `AttributeError`.

Also, I'm no longer maintain this project, so sorry I can't help you fix it.
